version: '3'

services:
  mongo:
    image: mongo
    ports:
      - "27018:27017"
    volumes:
      - data-volume:/data/db
  
  web:
    build: .
    command:
      - nodemon
      - ./bin/www
    ports:
      - "3000:3000"
    environment:
      - MONGO_HOST=mongo
      - NODE_ENV=development
    links:
      - mongo 
    depends_on: 
      - mongo
    volumes:
      - .:/home/ubuntu/rentomojo
      - node_modules:/home/ubuntu/rentomojo/node_modules

volumes:
  data-volume:
  node_modules: